12 دالة رئيسية:
├── createBook()
├── getAllBooks()
├── getBook()
├── updateBook()
├── deleteBook()
├── rateBook()
├── getTopViewed()
├── getTopRated()
├── getByCategory()
├── getByLanguage()
├── searchBooks()
└── getStatistics()